name: flutter_test_app
description: A Test code for Flutter app

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  integration_test:
    sdk: flutter
  test: ^1.14.4

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

